export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const GET_GREENHOUSES_START = "GET_GREENHOUSES_START";
export const GET_GREENHOUSES_SUCCESS = "GET_GREENHOUSES_SUCCESS";
export const GET_GREENHOUSES_FAIL = "GET_GREENHOUSES_FAIL";
