export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const GET_ACCOUNT_START = "GET_ACCOUNT_START";
export const GET_ACCOUNT_SUCCESS = "GET_ACCOUNT_SUCCESS";
export const GET_ACCOUNT_FAIL = "GET_ACCOUNT_FAIL";
export const CHANGE_PASSWORD_START = "CHANGE_PASSWORD_START";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";
export const GET_GREENHOUSES_START = "GET_GREENHOUSES_START";
export const GET_GREENHOUSES_SUCCESS = "GET_GREENHOUSES_SUCCESS";
export const GET_GREENHOUSES_FAIL = "GET_GREENHOUSES_FAIL";

export const GET_USERS_START = "GET_USERS_START";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAIL = "GET_USERS_FAIL";

export const GET_TABEL_START = "GET_TABEL_START";
export const GET_TABEL_SUCCESS = "GET_TABEL_SUCCESS";
export const GET_TABEL_FAIL = "GET_TABEL_FAIL";

export const GET_CELLS_START = "GET_CELLS_START";
export const GET_CELLS_SUCCESS = "GET_CELLS_SUCCESS";
export const GET_CELLS_FAIL = "GET_CELLS_FAIL";

export const OPEN_CELLS_START = "OPEN_CELLS_START";
export const OPEN_CELLS_SUCCESS = "OPEN_CELLS_SUCCESS";
export const OPEN_CELLS_FAIL = "OPEN_CELLS_FAIL";

export const ADD_USER_IN_TABEL_START = "ADD_USER_IN_TABEL_START";
export const ADD_USER_IN_TABEL_SUCCESS = "ADD_USER_IN_TABEL_SUCCESS";
export const ADD_USER_IN_TABEL_FAIL = "ADD_USER_IN_TABEL_FAIL";

export const DELETE_USER_IN_TABEL_START = "DELETE_USER_IN_TABEL_START";
export const DELETE_USER_IN_TABEL_SUCCESS = "DELETE_USER_IN_TABEL_SUCCESS";
export const DELETE_USER_IN_TABEL_FAIL = "DELETE_USER_IN_TABEL_FAIL";

export const TRY_SEND_CELLS_START = "TRY_SEND_CELLS_START";
export const TRY_SEND_CELLS_SUCCESS = "TRY_SEND_CELLS_SUCCESS";
export const TRY_SEND_CELLS_FAIL = "TRY_SEND_CELLS_FAIL";

export const GET_ORDERS_START = "GET_ORDERS_START";
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
export const GET_ORDERS_FAIL = "GET_ORDERS_FAIL";

export const GET_ORDER_PRODUCTS_START = "GET_ORDER_PRODUCTS_START";
export const GET_ORDER_PRODUCTS_SUCCESS = "GET_ORDER_PRODUCTS_SUCCESS";
export const GET_ORDER_PRODUCTS_FAIL = "GET_ORDER_PRODUCTS_FAIL";